### ISSUE TITLE
Add support for cilium only mode

### ISSUE THREAD

**Issue by Syntax3rror404** [stuttgart-things/deploy-configure-rke#3]
Add support for cilium only mode:

- [x] Remove nginx-ingress controller
- [x] Remove kube-proxy
- [ ] Add vars for the loadbalancer IP Range
- [ ] Add HelmChartConfig config for cilium
- [x] Change CNI in rke config to cilium

Example of a HelmChartConfig for cilium
`cat /var/lib/rancher/rke2/server/manifests/rke2-cilium-config.yaml`

```
---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    bgp:
      enabled: false
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
    ingressController:
      enabled: true
    k8sServiceHost: 127.0.0.1
    k8sServicePort: 6443
    kubeProxyReplacement: true
    l2announcements:
      enabled: true
    externalIPs:
      enabled: true
    ingressController:
      enabled: true
      service:
        name: cilium-ingress
        labels:
          l2: active
        type: LoadBalancer
        loadBalancerIP : 192.168.35.40
```

We also need to apply a few manifests to add the loadbalancer pools and also the policies for the L2Announcement
https://github.com/stuttgart-things/docs/blob/main/cilium.md
